apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/KatharinaSick/PresentationMaterials'
    path: 20230328-CloudNativeLinz/examples/00-init/applications
    targetRevision: HEAD
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
