# https://marketplace.upbound.io/providers/upbound/provider-gcp-storage/v0.37.0
apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  name: i-was-created-with-crossplane-and-gitops
spec:
  forProvider:
    location: EU
    labels:
      managed-by: argocd
  providerConfigRef:
    name: default