apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/KatharinaSick/PresentationMaterials'
    path: 20231011-ViennaDataEngineeringMeetup/demos/03-gitops/applications/simple-app
    targetRevision: HEAD
  destination:
    namespace: simple-app
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
